create table public.reclamaciones (
  id bigint generated by default as identity primary key,
  tracking_code text not null unique,
  created_at timestamptz not null default now(),
  full_name text not null,
  document_type text not null,
  document_number text not null,
  phone text not null,
  email text not null,
  address text not null,
  is_minor boolean not null default false,
  representative_name text,
  item_type text not null,
  item_description text not null,
  amount numeric(12,2) not null,
  claim_type text not null,
  detail text not null,
  request text not null,
  constraint reclamaciones_tracking_length check (char_length(tracking_code) between 12 and 30),
  constraint reclamaciones_name_length check (char_length(trim(full_name)) between 3 and 120),
  constraint reclamaciones_document_type check (document_type in ('DNI', 'CE', 'Pasaporte')),
  constraint reclamaciones_document_length check (char_length(trim(document_number)) between 6 and 20),
  constraint reclamaciones_phone_length check (char_length(trim(phone)) between 6 and 20),
  constraint reclamaciones_email_length check (char_length(trim(email)) between 5 and 120),
  constraint reclamaciones_address_length check (char_length(trim(address)) between 3 and 180),
  constraint reclamaciones_representative check (not is_minor or (representative_name is not null and char_length(trim(representative_name)) between 3 and 120)),
  constraint reclamaciones_item_type check (item_type in ('Producto', 'Servicio')),
  constraint reclamaciones_item_length check (char_length(trim(item_description)) between 3 and 500),
  constraint reclamaciones_amount check (amount between 0 and 999999.99),
  constraint reclamaciones_claim_type check (claim_type in ('Reclamo', 'Queja')),
  constraint reclamaciones_detail_length check (char_length(trim(detail)) between 3 and 1500),
  constraint reclamaciones_request_length check (char_length(trim(request)) between 3 and 1000)
);

alter table public.reclamaciones enable row level security;

revoke all on table public.reclamaciones from anon, authenticated;
grant insert (
  tracking_code, full_name, document_type, document_number, phone, email,
  address, is_minor, representative_name, item_type, item_description,
  amount, claim_type, detail, request
) on table public.reclamaciones to anon, authenticated;
grant usage, select on sequence public.reclamaciones_id_seq to anon, authenticated;

create policy "Registrar reclamaciones"
on public.reclamaciones
for insert
to anon, authenticated
with check (
  char_length(tracking_code) between 12 and 30
  and char_length(trim(full_name)) between 3 and 120
  and document_type in ('DNI', 'CE', 'Pasaporte')
  and char_length(trim(document_number)) between 6 and 20
  and char_length(trim(phone)) between 6 and 20
  and char_length(trim(email)) between 5 and 120
  and char_length(trim(address)) between 3 and 180
  and (not is_minor or (representative_name is not null and char_length(trim(representative_name)) between 3 and 120))
  and item_type in ('Producto', 'Servicio')
  and char_length(trim(item_description)) between 3 and 500
  and amount between 0 and 999999.99
  and claim_type in ('Reclamo', 'Queja')
  and char_length(trim(detail)) between 3 and 1500
  and char_length(trim(request)) between 3 and 1000
);
